type Column = { key: string; label: string };
type Row = Record<string, string | number>;

export function DocumentSheet({
  title,
  subtitle,
  columns,
  rows,
}: {
  title: string;
  subtitle?: string;
  columns: Column[];
  rows: Row[];
}) {
  return (
    <div className="mx-auto w-full max-w-3xl border border-black bg-white p-6 text-black">
      <div className="text-center">
        <div className="text-base font-bold uppercase tracking-wide">
          State Farming Corporation of Kerala Ltd.
        </div>
        <div className="mt-2 border-t border-b border-black py-1 text-sm font-semibold uppercase">
          {title}
        </div>
        {subtitle && <div className="mt-1 text-xs">{subtitle}</div>}
        <div className="mt-1 text-[10px] text-slate-600">
          Demo — generated by SFCK Plantation ERP
        </div>
      </div>

      <table className="mt-4 w-full border-collapse text-xs">
        <thead>
          <tr>
            {columns.map((c) => (
              <th
                key={c.key}
                className="border border-black bg-slate-50 px-2 py-1 text-left font-semibold"
              >
                {c.label}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((r, i) => (
            <tr key={i}>
              {columns.map((c) => (
                <td key={c.key} className="border border-black px-2 py-1">
                  {r[c.key] ?? '—'}
                </td>
              ))}
            </tr>
          ))}
          {!rows.length && (
            <tr>
              <td colSpan={columns.length} className="border border-black px-2 py-4 text-center text-slate-500">
                No data in scope.
              </td>
            </tr>
          )}
        </tbody>
      </table>
    </div>
  );
}
