type Line = {
  checkRoll: string;
  name: string;
  category: string;
  gross: number;
  incentive: number;
  weightage: number;
  washing: number;
  pf: number;
  other: number;
  net: number;
};

function Amount({ value }: { value: number }) {
  return <span className="tabular-nums">₹{value.toFixed(2)}</span>;
}

export function PayslipMalayalam({ line, period }: { line: Line; period: { start: string; end: string } }) {
  return (
    <div className="mx-auto w-full max-w-md border border-black bg-white p-5 text-black">
      <div className="text-center">
        <div className="text-base font-bold" style={{ fontFamily: 'var(--font-ml)' }}>
          സ്റ്റേറ്റ് ഫാമിംഗ് കോർപ്പറേഷൻ ഓഫ് കേരള
        </div>
        <div className="text-xs">State Farming Corporation of Kerala Ltd.</div>
        <div className="mt-2 border-t border-b border-black py-1 text-sm font-semibold" style={{ fontFamily: 'var(--font-ml)' }}>
          ശമ്പള സ്ലിപ്പ്
          <span className="ml-1 font-normal">(Payment Slip)</span>
        </div>
      </div>

      <table className="mt-3 w-full text-xs">
        <tbody>
          <tr>
            <td className="py-1 font-medium" style={{ fontFamily: 'var(--font-ml)' }}>പേര്</td>
            <td className="py-1 text-right">{line.name}</td>
          </tr>
          <tr className="border-t border-dashed border-black/40">
            <td className="py-1 font-medium" style={{ fontFamily: 'var(--font-ml)' }}>ചെക്ക് റോൾ നമ്പർ</td>
            <td className="py-1 text-right">{line.checkRoll}</td>
          </tr>
          <tr className="border-t border-dashed border-black/40">
            <td className="py-1 font-medium" style={{ fontFamily: 'var(--font-ml)' }}>വിഭാഗം</td>
            <td className="py-1 text-right">{line.category}</td>
          </tr>
          <tr className="border-t border-dashed border-black/40">
            <td className="py-1 font-medium" style={{ fontFamily: 'var(--font-ml)' }}>കാലയളവ്</td>
            <td className="py-1 text-right">{period.start} – {period.end}</td>
          </tr>
        </tbody>
      </table>

      <div className="mt-3 border-t border-black pt-2 text-sm font-semibold" style={{ fontFamily: 'var(--font-ml)' }}>
        വരുമാനം <span className="ml-1 font-normal text-xs">(Earnings)</span>
      </div>
      <table className="w-full text-xs">
        <tbody>
          <tr>
            <td className="py-1" style={{ fontFamily: 'var(--font-ml)' }}>അടിസ്ഥാന വേതനം</td>
            <td className="py-1 text-right"><Amount value={line.gross} /></td>
          </tr>
          <tr className="border-t border-dashed border-black/40">
            <td className="py-1" style={{ fontFamily: 'var(--font-ml)' }}>ഇൻസെന്റീവ്</td>
            <td className="py-1 text-right"><Amount value={line.incentive} /></td>
          </tr>
          <tr className="border-t border-dashed border-black/40">
            <td className="py-1" style={{ fontFamily: 'var(--font-ml)' }}>വെയിറ്റേജ് അലവൻസ്</td>
            <td className="py-1 text-right"><Amount value={line.weightage} /></td>
          </tr>
          <tr className="border-t border-dashed border-black/40">
            <td className="py-1" style={{ fontFamily: 'var(--font-ml)' }}>വാഷിംഗ് അലവൻസ്</td>
            <td className="py-1 text-right"><Amount value={line.washing} /></td>
          </tr>
        </tbody>
      </table>

      <div className="mt-3 border-t border-black pt-2 text-sm font-semibold" style={{ fontFamily: 'var(--font-ml)' }}>
        കിഴിവുകൾ <span className="ml-1 font-normal text-xs">(Deductions)</span>
      </div>
      <table className="w-full text-xs">
        <tbody>
          <tr>
            <td className="py-1" style={{ fontFamily: 'var(--font-ml)' }}>പ്രോവിഡന്റ് ഫണ്ട് (PF)</td>
            <td className="py-1 text-right"><Amount value={line.pf} /></td>
          </tr>
          <tr className="border-t border-dashed border-black/40">
            <td className="py-1" style={{ fontFamily: 'var(--font-ml)' }}>മറ്റ് കിഴിവുകൾ</td>
            <td className="py-1 text-right"><Amount value={line.other} /></td>
          </tr>
        </tbody>
      </table>

      <div className="mt-3 flex items-center justify-between border-t-2 border-black pt-2 text-sm font-bold">
        <span style={{ fontFamily: 'var(--font-ml)' }}>അറ്റ വേതനം <span className="font-normal text-xs">(Net Pay)</span></span>
        <span className="text-base"><Amount value={line.net} /></span>
      </div>

      <div className="mt-3 border-t border-black pt-2 text-center text-[10px] text-slate-600">
        Generated by SFCK Plantation ERP (Demo)
      </div>
    </div>
  );
}
